---
title: "EDA"
---

```{r}
#| label: load-packages
library(tidyverse)
library(tidymodels)
library(readxl)
```

```{r}
#| label: load-data
edu_achievement <- read_excel(
  "data/educationachievement.xlsx",
  skip = 1
)
glimpse(edu_achievement)
```

```{r}
#| label: pivot-longer
edu_achievement_longer <- edu_achievement |>
  pivot_longer(
    cols = c("Dalc", "Walc"),
    names_to = "alc_type",
    values_to = "alc_lvl"
  )
```

```{r}
#| label: g3-failures-plot
ggplot(edu_achievement, aes(x = failures, y = G3, group = failures, color = failures)) +
  geom_boxplot() +
  labs(
    title = "Final Grade vs Number of Past Class Failures",
    x = "Number of Past Class Failures",
    y = "Final Grade"
  ) +
  theme(legend.position = "none")
```

```{r}
#| label: wacl-dalc-g3-plot
new_labels <- c("Dalc" = "Weekday", "Walc" = "Weekend")

edu_achievement_longer |>
  mutate(
    alc_type = fct_relevel(alc_type, c("Dalc", "Walc"))
  ) |>
ggplot(aes(x = alc_lvl, y = G3, group = alc_lvl, color = alc_lvl)) +
  geom_boxplot() +
  facet_grid(rows = vars(alc_type), labeller = labeller(.rows = new_labels)) +
  labs(
    title = "Final Grade vs Alcoholic Consumption Level",
    subtitle = "Separated by Weekday and Weekend",
    x = "Alcoholic Consumption Level",
    y = "Final Grade"
  ) +
  theme(legend.position = "none")
```

```{r}
#| label: medu-g3-plot
ggplot(edu_achievement, aes(x = Medu, y = G3)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  labs(
    x = "Mother’s Education Level",
    y = "Final Grade (1-20)",
    title = "Final Grade of Students Based on Mother’s Education Level",
    subtitle = "Student Serformance in Math in the Portugueuse schools of 
Gabriel Pereira and Mousinho da Silveira"
  )

ggplot(edu_achievement, aes(x = Fedu, y = G3)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  labs(
    x = "Father’s Education Level",
    y = "Final Grade (1-20)",
    title = "Final Grade of Students Based on Father’s Education Level",
    subtitle = "Student Serformance in Math in the Portugueuse schools of 
Gabriel Pereira and Mousinho da Silveira"
  )
```

```{r}
#| label: internet-g3-plot
ggplot(edu_achievement, aes(x = internet, y = G3, fill = internet)) +
  geom_boxplot(alpha = 0.7) +
  labs(
    title = "Distribution of Final Grades (G3) by Internet Access",
    x = "Internet Access",
    y = "Final Grade (G3)"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

```


```{r}
#| label: paid-g3-plot
#| message: false
ggplot(edu_achievement, aes(x = paid, y = G3)) +
  geom_boxplot()
```


```{r}
#| label: freetime-g3-plot
#| message: false
ggplot(edu_achievement, aes(x = freetime, y = G3)) +
  geom_point()
```

